### ISSUE TITLE
Issue with transfer submission

### ISSUE THREAD

**Issue by Ade92** [ketola/jlibra#10]
I'm submitting a transaction using admission control grpc, but the transaction submission does not generate any events. I'm checking against libra cli and librabrowser.io and nothing appears. ac_status is Accepted, mempool status is Valid and no error appears. I'm also trying your TransferExample but still no event appears.  Is there something that I'm missing?

**Comment by ice09** [comment]
We rarely had this happen as well, just to be sure, can you insert
`Thread.sleep (5000)` after the last statement in the `TransferExample`

Ade92 <notifications@github.com> schrieb am Di., 9. Juli 2019, 16:24:

**Comment by Ade92** [comment]
Yes, indeed, that solved the problem. Thanks a lot.

**Comment by ice09** [comment]
Thanks for the feedback, will add a known issues section in the README. Must be a main thread termination problem, but as the examples are just meant to show library usage, this workaround is fine for now.
