### ISSUE TITLE
Maven Release 

### ISSUE THREAD

**Issue by mgrant34** [ketola/jlibra#123]
Hello,

Looks like the last release way on May 12th. Can you please do a new maven release with latest changes?

**Comment by ketola** [comment]
@mgrant34, I noticed you already closed the issue, but I think this is a valid one. There was a period when the Libra api was changing quite often but now it's been stable for a while. I will make the new release this weekend or early next week :+1:

**Comment by ketola** [comment]
A new version 0.10.0 has now been deployed
