### ISSUE TITLE
Change API get_account_state to get_account

### ISSUE THREAD

**Issue by mkibaly** [ketola/jlibra#124]
According to last update on libra testnet
[Testnet push announcement for 07/23](https://community.libra.org/t/testnet-push-announcement-for-07-23/3024)

The Json-RPC API is changed from **get_account_state** to **get_account**

Additionally, they added /v1 for JSONRPC endpoint, but they will redirect to latest API version if not present.

**Comment by ketola** [comment]
Hi @mkibaly and thank you for the interest in the project. I have created a new branch https://github.com/ketola/jlibra/tree/testnet-20200723 where I have been working on the changes required after the testnet update. 
I will fix this issue as part of the changes required. The renaming of the get_account_state method has been done, but the url has not been fixed yet.
If you're are interested in contributing, please let me know.

**Comment by mkibaly** [comment]
Thanks @ketola for invitation, but actually i don't have experience on java language. I'm working on building C# Libra SDK
