### ISSUE TITLE
Null pointer exception on `accountState.sequenceNumber()`

### ISSUE THREAD

**Issue by ninobonev85** [ketola/jlibra#136]
An exception occurs when trying to run the example. Any ideas why and how to solve this?

```
Exception in thread "main" java.lang.NullPointerException
	at dev.jlibra.example.TransferExample.main(TransferExample.java:66)

```
https://github.com/ketola/jlibra/blob/c0acc83efafe74f9f27a9ec7489a9d7bcd11ad7c/jlibra-examples/src/main/java/dev/jlibra/example/TransferExample.java#L66

**Comment by ketola** [comment]
Hi,
The first issue is probably that the account does not exist yet (getAccount returns null and you get an exception). That example does not create the account like some examples do, you should create the account by using the mint example or create child account example. You can also take a look at the integration test module as it has a full test that creates accounts and transfers money between them. 

You can also try to follow the step-by-step example from https://github.com/ketola/jlibra/blob/master/docs/HOWTO.md 

Let me know if this helps

**Comment by ketola** [comment]
@ninobonev85, I also now noticed that I had not updated the TransferExample when the auth_key_prefix parameter was dropped, so the example was actually broken. I created a fix for it: https://github.com/ketola/jlibra/pull/137, I will merge the fix and if you pull the changes you should see the example working.

**Comment by ninobonev85** [comment]
Yes, it's all working fine now after this fix. One last question. If I have a Libra account with `id`, `userKey`, **account** with `address`, `authenticationKey`, etc. how can I get the `PublicKey` and `PrivateKey` using `JLibra` or how to do the transfer without them?

**Comment by ketola** [comment]
If you have used the libra command-line client to create the account, the client stores the keys somewhere, I have not looked into it, but it also provides a 'mnemonic' to restore the account. If you have that, you can try this example to get the keys: https://github.com/ketola/jlibra/blob/master/jlibra-examples/src/main/java/dev/jlibra/example/ImportAccountMnemonicExample.java

Based on this documentation the mnemonic file can be located in directory of the libra wallet: https://github.com/libra/libra/blob/master/developers.libra.org/docs/reference/libra-cli.md#run-a-cli-client-to-connect-to-any-libra-network
