### ISSUE TITLE
Unify the use of value objects in the project

### ISSUE THREAD

**Issue by ketola** [ketola/jlibra#19]
Currently, there are several different ways of creating value objects and setting values to them (public constructors, builder methods, values in constructor, getters/setters etc). Propose a project-wide pattern for the value objects and fix the current implementation to follow this pattern.

**Comment by ketola** [comment]
I did some research on the value object patterns and if I want it to be good, I need to make it clear which attributes are required so that it is obvious for the developer and also using the builder pattern makes the value objects more expressive. But implementing that in pure java results in lots of code with all the builders and validations.

So I compared different libraries like lombok that was suggested earlier. It should be possible to use these so that they don't become transitive dependencies for other projects. But I found an interesting alternative that I want to give a try: https://immutables.github.io/

Here's couple of posts about it:
https://medium.com/@GrindrLabs/you-should-be-using-immutables-311cdda48f7f
and 
https://medium.com/@vgonzalo/dont-use-lombok-672418daa819

**Comment by ice09** [comment]
I am very fine with Immutables. But I would also be fine with no framework, as your initial argument is very valid. But if it's interface based, it should introduce no problem.

**Comment by ketola** [comment]
I will try it out for a couple of classes and see how it looks like, I will push it to a separate branch for you to see as well, we can then decide is it worth using. I'll also see what it requires from the ide / dev environment.

**Comment by hczerpak** [comment]
I haven't used Immutables but it's looking interesting.
