### ISSUE TITLE
Create an integration test for jlibra

### ISSUE THREAD

**Issue by ketola** [ketola/jlibra#27]
We should have integration tests to know if there have been breaking changes in the libra api or errors in our code that have been missed by unit tests.

For this:
- create a new jlibra-integration-tests module
- the tests of this module should not be run during the normal build (mvn install, mvn verify), instead, the tests should require defining another goal or maven profile
- The first test could create two key pairs, mint libras for one of the accounts, transfer it to the other and verify the transaction.

**Comment by hczerpak** [comment]
If I use maven-failsafe-plugin to run IT tests it would run in `integration-test` phase. I think it is a good standard way of doing it. What do you think?

**Comment by ketola** [comment]
Yes, that sounds good. I just wanted it to have a way to run only unit tests for example for each branch but we might do integration tests scheduled. But I guess that should be possible with your suggestion.

**Comment by hczerpak** [comment]
resolved
