### ISSUE TITLE
Investigate benefits of connection pooling

### ISSUE THREAD

**Issue by ketola** [ketola/jlibra#31]
Investigate is there any benefits of the pooling the grpc api connections. Are there any ready-made libraries for this?

**Comment by hczerpak** [comment]
Found [this](https://github.com/grpc/grpc-java/issues/3268) discussion on grpc-java where [Eric Gribkoff](https://github.com/ericgribkoff) from Google says:

> Channels are expensive to create, and the general recommendation is to use one per application, shared among the service stubs.

IMO this should be enough for us as a guideline about Channels/ManagedChannels. Our `AdmissionControl` class requires ManagedChannel as constructor parameter.

**Comment by ketola** [comment]
Ok, I will close this issue.
