### ISSUE TITLE
Add logging framework to replace uses of System.out

### ISSUE THREAD

**Issue by hczerpak** [ketola/jlibra#33]
I think this is everyone sees coming. We need to introduce a logging framework. In some places it is necessary to log warnings or errors

**Comment by ketola** [comment]
I have not used it before but seems Log4J 2 api + logging implementation promises many improvements over others, while compatible with older frameworks: https://logging.apache.org/log4j/2.x/

**Comment by hczerpak** [comment]
I like it. Lazy logging is cool
