### ISSUE TITLE
In TransferExample  result.getVmStatus() is giving Unexpected Result

### ISSUE THREAD

**Issue by tk1993** [ketola/jlibra#47]
SubmitTransactionResult result = admissionControl.submitTransaction(publicKey, privateKey,transaction);

gives ==>
Admission control status: Accepted
Mempool status: Valid
VM status: validation {
  code: UnknownScript
  message: "none"
}

Tried by increasing maxGasAmount but still getting same error

**Comment by ice09** [comment]
Is this a transaction against a local or the official testnet?

**Comment by tk1993** [comment]
> Is this a transaction against a local or the official testnet?

Its on testnet.

**Comment by ice09** [comment]
Then it might be related to the recent changes on the testnet: https://community.libra.org/t/testnet-update-september-4th/1630?u  
I assume this will take some time to catch on, maybe @ketola can add to this?

**Comment by ketola** [comment]
I fixed the library after the changes on 4th September so I guess testnet was updated. Usually the unknown script error is fixed by re compiling the transfer.move script.
I'll try to take a look at this soon, hopefully tomorrow.

**Comment by ketola** [comment]
Also, @tk1993, did you use the latest release or the master branch? Because I haven't created a new release since the latest fix.

**Comment by tk1993** [comment]
@ketola I am using "testnet" branch

**Comment by ketola** [comment]
I meant which version of JLibra? Did you build it from master or use the latest version in maven repo? The latest release does not contain the latest fixes, so If you used that, try building JLibra by yourself until I have created a new release.

**Comment by ketola** [comment]
Ok, I tested the transaction with the master branch and then released a new version. @tk1993, you can now upgrade to version 0.2.0 and it should work.

**Comment by tk1993** [comment]
@ketola I was using version 0.1.1-SNAPSHOT of Libra earlier 
Thanks for new version 0.2.0 Transaction is working fine on this. 
@ketola Thanks for the quick response I really appreciate :)
