### ISSUE TITLE
can't find class at newest version code

### ISSUE THREAD

**Issue by asdgh1000** [ketola/jlibra#48]
can't find
 ImmutableGetAccountState 
 ImmutableQuery
ImmutableProgram 
ImmutableTransaction
in dev.jlibra.admissioncontrol.query.

**Comment by ice09** [comment]
Those are generated classes, please make sure to clone the complete repo and build with `mvn install` then all classes should be generated in correct order.

**Comment by ketola** [comment]
Yes, those classes are generated by the Immutables library https://immutables.github.io/

They should be generated by following the instructions of @ice09 and at least Intellij and Eclipse are known to work. 

I could try to make the instructions more clear about this.

**Comment by ketola** [comment]
I added a line about the importance of running the maven build.
