### ISSUE TITLE
result.getAccountTransactionsBySequenceNumber().size() always equals to 1

### ISSUE THREAD

**Issue by straumat** [ketola/jlibra#49]
Hello, first of all, thanks for your work ! 

I'm using 0.1.1 snapshot and when doing this : 
```
UpdateToLatestLedgerResult result = admissionControl.updateToLatestLedger(ImmutableQuery.builder()
				.addAccountTransactionBySequenceNumberQueries(
						ImmutableGetAccountTransactionBySequenceNumber.builder()
								.accountAddress(Hex.decode(address))
								.sequenceNumber(sequenceNumber)
								.build())
				.build());
System.out.println(result.getAccountTransactionsBySequenceNumber().size());
```
I always have 1 result even if the sequence for the address doesn't exists : `SignedTransactionWithProof{senderPublicKey=[], senderSignature=[], events=[]}`

Is it normal ? From my point of view, i should have no results at all no ?

**Comment by hczerpak** [comment]
Thanks for submitting this. I think that should be empty. I'll have a look at this.
