### ISSUE TITLE
Impossible to create a new transaction

### ISSUE THREAD

**Issue by straumat** [ketola/jlibra#51]
Since on or two days, my code that creates transaction using your library wasn't working anymore... I thought i was crazy because all worked fine but now i have a "submit txn rejected" error everytime.

So i get your sources again and after doing `mvn verify`, i get : 
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running dev.jlibra.SimpleTransactionIT
08:16:07.614| Balance for 0703a61585597d9b56a46a658464738dff58222b4393d32dd9899bedb58666e9 is 1000000000
08:16:07.622| Generated seed: vital unable dish comic grocery blush invest gun two wolf stand range zoo domain milk renew soup photo
Transaction submitted with result: SubmitTransactionResult{admissionControlStatus=code: Rejected
message: "submit txn rejected"
, mempoolStatus=, vmStatus=, statusCase=AC_STATUS}
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 17.401 s <<< FAILURE! - in dev.jlibra.SimpleTransactionIT
[ERROR] transferTest(dev.jlibra.SimpleTransactionIT)  Time elapsed: 17.054 s  <<< FAILURE!
java.lang.AssertionError: expected:<Accepted> but was:<Rejected>
	at dev.jlibra.SimpleTransactionIT.transfer(SimpleTransactionIT.java:164)
	at dev.jlibra.SimpleTransactionIT.transferTest(SimpleTransactionIT.java:107)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   SimpleTransactionIT.transferTest:107->transfer:164 expected:<Accepted> but was:<Rejected
```

Seems something change with libra

**Comment by straumat** [comment]
In fact, when i check my history, i think Libra changed something this afternoon :)

**Comment by hczerpak** [comment]
I'm sure it worked on Tuesday 3 days ago 😂 They keep changing it...

**Comment by ketola** [comment]
It looks like the version in testnet is using the new serialization for transactions too. I can try to take a look at this.

**Comment by ketola** [comment]
I was able to get the transfer transaction working but I still have some work to do with the tests and some of the examples. I pushed the current changes to https://github.com/ketola/jlibra/tree/transaction-serialization

**Comment by straumat** [comment]
It's a bit strange, seems AccountState & AddressArgument are no more available ?

**Comment by javadance** [comment]
Then, how can I fix that 'TransferExample' ??

**Comment by javadance** [comment]
I failed to build 'transaction-serialization' branch. Is there any clue ?

**Comment by ketola** [comment]
Yes, I actually noticed already yesterday that the transactions were not going through. First problem was that the public key was set wrong in the transaction and after that, the next problem was that the transaction script needs to be recompiled.
The error message in the result has been changed, now it will just return a number which needs to be checked from libra source what it actually means. 
But I will continue working on the branch and hopefully get it to work at some point.

**Comment by ketola** [comment]
The implementation in the transaction-serialization branch is now working so you can pull that and build it yourself until the changes are in master and released

**Comment by javadance** [comment]
Thanks, @ketola.
But when I tested your new fix, it still doesn't work in trasferring.
I created two accounts, minted to first account and then transfer to second account.
But it doesn't work.  Please let me know what I've missed.

**Comment by ketola** [comment]
At least the integration test was working yesterday, is it working for you? Make sure you set the correct sequence number for the transaction. The libra api does not give good error messages in the response anymore so it is not always so clear what is the problem.

**Comment by javadance** [comment]
@ketola,
Can I paste the I tested here? 
I write a simple SpringBoot code below and this is not working with your latest fix.
Basically, it is same to your code example.


`@PostMapping("/account/transfer")
    public String transfer(String payeeAddress, String publicKeyStr, String privateKeyStr, String amount) {


        try {
            Security.addProvider(new BouncyCastleProvider());

            PrivateKey privateKey = KeyUtils.privateKeyFromHexString(privateKeyStr);
            PublicKey publicKey = KeyUtils.publicKeyFromHexString(publicKeyStr);

            int sequenceNumber = 2;

            logger.info("Sending from {} to {}", toHexStringLibraAddress(publicKey.getEncoded()), payeeAddress);

            ManagedChannel channel = ManagedChannelBuilder.forAddress("ac.testnet.libra.org", 8000)
                    .usePlaintext()
                    .build();

            AdmissionControl admissionControl = new AdmissionControl(channel);

            // Arguments for the peer to peer transaction
            U64Argument amountArgument = new U64Argument(Long.parseLong(amount) * 1000000);
            AccountAddressArgument addressArgument = new AccountAddressArgument(Hex.decode(payeeAddress));

            Transaction transaction = ImmutableTransaction.builder()
                    .sequenceNumber(sequenceNumber)
                    .maxGasAmount(160000)
                    .gasUnitPrice(1)
                    .senderAccount(KeyUtils.toByteArrayLibraAddress(publicKey.getEncoded()))
                    .expirationTime(Instant.now().getEpochSecond() + 60)
                    .program(
                            ImmutableProgram.builder()
                                    .code(ByteString.copyFrom(Move.peerToPeerTransferAsBytes()))
                                    .addArguments(addressArgument, amountArgument)
                                    .build())
                    .build();

            SignedTransaction signedTransaction = ImmutableSignedTransaction.builder()
                    .publicKey(KeyUtils.stripPublicKeyPrefix(publicKey.getEncoded()))
                    .transaction(transaction)
                    .signature(LibraHelper.signTransaction(transaction, privateKey))
                    .build();

            SubmitTransactionResult result = admissionControl.submitTransaction(signedTransaction);

            logger.info(result.toString());
            logger.info("Status type: {}", result.getStatusCase());
            logger.info("Admission control status: {}", result.getAdmissionControlStatus());
            logger.info("Mempool status: {}", result.getMempoolStatus());
            logger.info("VM status: {}", result.getVmStatus());
//            AdmissionControlOuterClass.SubmitTransactionResponse.StatusCase statusCase = result.getStatusCase();

            Thread.sleep(3000);
            channel.shutdown();
            Thread.sleep(3000); // add sleep to prevent premature closing of channel


        } catch(Exception e) {
            logger.error(e.getMessage());
        }

        return "";
    }`

**Comment by ketola** [comment]
You cannot hard code the sequence number to be 2 because it will change after each successful transfer and the transfer will fail if it's not the correct one. 
You can combine the GetAccountStateExample with your code (same way as it is done in the integration test). First, get the account state and get the sequence number from there and use that in your transfer.

**Comment by javadance** [comment]
@ketola,
5 min ago, I changed that hard coded block like your code(SimpleTransactionIT.java) like below.

long sequenceNumber = maybeFindSequenceNumber(admissionControl, payeeAddress);

But it's still submit errors. :(   What did I still missing ?

**Comment by javadance** [comment]
@ketola,
Ah, I miunderstood API.
I fixed above code like below and finally it's working.

long sequenceNumber = maybeFindSequenceNumber(admissionControl,  **payer**);

Thanks a lot. ^^  You helped me out 👍

**Comment by ice09** [comment]
If you are using Spring Boot for jlibra, maybe these projects can help you, would be very interested to get feedback:

- https://github.com/ice09/jlibra-spring-boot-starter (Start Project which eases dev with Spring Boot and jlibra)
- https://github.com/ice09/java-libra-client (Spring Shell client using Starter project)

**Comment by javadance** [comment]
@ice09,
Yeah, I got interest in jlibra-spring-boot-starter project too. 👍 
I'll try that next time.

**Comment by hczerpak** [comment]
I also run `transaction-serialization` branch and all tests and examples are running fine. I think we can close.
