### ISSUE TITLE
Wrong value when retrieving getBalanceInMicroLibras()

### ISSUE THREAD

**Issue by straumat** [ketola/jlibra#61]
When using your example [GetAccountStateExample](https://github.com/ketola/jlibra/blob/master/jlibra-examples/src/main/java/dev/jlibra/example/GetAccountStateExample.java) with an address with lots of libras : [da2f86f7ee9b10317fd1d1ad31f5059efceb97589042be20a817be26d5be06b3](https://libexplorer.com/address/da2f86f7ee9b10317fd1d1ad31f5059efceb97589042be20a817be26d5be06b3).

The accountResource.getBalanceInMicroLibras() returns 1073435 but if you check in libra explorer, the value is 19,001.073435

**Comment by ketola** [comment]
I checked a few big accounts from https://libraview.org/TopList/0 and I got the same balance for them with the GetAccountStateExample.

The account that you mentioned only had about 249 libras and for that I also got the same result. Could you provide another example where balance is wrong and can you confirm my tests or are you getting still different results?

**Comment by straumat** [comment]
I'm sorry, it seems there was no error even if i double checked everything before subumting this issue. Sorry again.
