### ISSUE TITLE
Create an example of txn_range

### ISSUE THREAD

**Issue by zebei** [ketola/jlibra#76]
please
Please add an example of:
Get the committed transactions by version range.
this in libra client :(query txn_range)

**Comment by ketola** [comment]
Currently, JLibra does not support that query but I checked from the grpc api what it would require to implement this:
- This is supported by the GetTransactions request item parameter in the updateToLatestLedgerResult method. It takes startVersion (long), limit (long) and fetchEvents (boolean) as parameters

JLibra would require 
- a new request item class (GetTransactions)
- an Optional List of GetTransaction request items in the Query class
- conversion to grpc request and from grpc response
- an example

**Comment by ketola** [comment]
Thanks for the PR @zebei! I will try to take a look at it tomorrow.
