### ISSUE TITLE
Key rotation

### ISSUE THREAD

**Issue by Ade92** [ketola/jlibra#9]
How did you manage to perform key rotation? 
I tried submitting a transaction doing key rotation, but I got stuck.
I tried creating a new keypair with private key K_s and public key K_v. I’m creating a raw transaction where the program contains the code for rotate_authentication_key and as argument the sha3(K_v) with argument type byte array. I’m also setting the sender's account. Then, I’m creating a signed transaction with raw transaction bytes, sender public key(K_v) and sender signature (raw transaction signed with K_s) and submit it to admission control. The issue is I’m getting an InvalidAuthKey error. Is there something I’m missing or that I’m doing wrong?

**Comment by ketola** [comment]
Here's the complete example for the transaction: https://github.com/ketola/jlibra/blob/master/src/main/java/dev/jlibra/example/TransferExample.java

You did not mention setting the salt in the signed data, do you have that? If you can upload your code to your repo and send a link, I might be able to get a better idea of what you're doing and what is the problem.

**Comment by ice09** [comment]
Don't really get what you are trying to do, did you look into the `TransferExample` to see how your requirement could fit in?  
Could you provide links or code snippets for what you are trying to achieve?

**Comment by Ade92** [comment]
In TransferExample you have a private key, a public key and a toAddress already set. Did you create a new account (toAddress) setting this keypair on it or did you perform a key rotation? If you set another toAddress there or another keypair, the transaction submission gets rejected. 

I already have an account created from libra cli, but I do not know the private key for this account, that’s why I’m trying to perform a key rotation so that I can set my own private and public keys on it and be able to submit transactions from this account. Here https://community.libra.org/t/key-rotation/706 the first answer to the question states that if we already have an account, we can perform a key rotation which decouples the authentication key from the account address and then submit transactions from this account.

So, I'm not sure if I'm on the right track here.

**Comment by ketola** [comment]
If you create a new key pair, then that is the account and you create the address by removing the first 12 bytes of the public key (the address is 32 bytes long (all of this you can find in the example). You don't need the libra cli to create the account.
The key rotation is not required for basic usage, you can create transactions without it. 

In my examples there's also a key pair generation example that prints out the address also, you can use that to create new accounts. To put initial libra to your account, you can use the minting feature of the libra cli.

**Comment by ice09** [comment]
jlibra (for now) uses no accounts as described in the CLI reference or as you know it from wallets. It uses plain private keys, the address is derived from these keys. Key rotation is not possible, as no "real account" is created, so no Resource `LibraAccount.T` is deployed.  
In Ethereum, you can compare it to using "private key" access in MEW: https://www.myetherwallet.com/access-my-wallet (which is not suggested for production and unsecure). MEW derives the address then and no other storage mechanism is used.  
If you somehow must do it your way (creating an account in CLI and using this one), until private keys can be exported, you could try to go through a "mnemonic phrase" as this is supported by the CLI. So you could create a new wallet "externally", export the mnemomic phrase and import it again in the CLI. But there are many things to consider (how is the mnemonic phrase stored, the derivation path, ...)
There is some information here: https://medium.com/cosmostation/the-magic-behind-a-mnemonic-phrase-and-hd-wallets-let-us-explain-43d9c97f6098

For now, I would just go with generated keys.

**Comment by Ade92** [comment]
Thank you for you explanations! 

I’m trying to create an account based on your explanations and examples.
This is what I have:

```
String create_account_script = "4c49425241564d0a010007014a00000004000000034e000000060000000c54000000050000000d5900000004000000055d0000002c00000004890000002000000007a90000000d00000000000001000200010300020002040203020402063c53454c463e0c4c696272614163636f756e74046d61696e126372656174655f6e65775f6163636f756e7400000000000000000000000000000000000000000000000000000000000000000001020004000c000c01110102";
        String existingAddress = "641b01502c34e42f6cd2b91ccdaacf18edd10ddaa875b814bc38817f9c9b3326";

        String freshAddress = "e27f0864f67b609ffc99fcd0dca09e6af0497e0c5d88611b7c061e2c0da37d50";
        PrivateKey privateKey = privateKeyFromHexString(
                "3051020101300506032b657004220420837677d6a21fa3f13b49901e9ed84440173469d70b80a2cf9fd9ea2e3ad497e6812100873f44ef1fb9dc26a1637efd66854a886c135d64c3e449b0d5a551d63132cb7d");
        PublicKey publicKey = publicKeyFromHexString(
                "302a300506032b6570032100873f44ef1fb9dc26a1637efd66854a886c135d64c3e449b0d5a551d63132cb7d");
        AdmissionControlGrpc.AdmissionControlBlockingStub stub = AdmissionControlGrpc.newBlockingStub(channel);


        Transaction.TransactionArgument freshAddressArgument = Transaction.TransactionArgument.newBuilder()
                .setType(Transaction.TransactionArgument.ArgType.ADDRESS)
                .setData(ByteString.copyFrom(Hex.decode(freshAddress)))
                .build();

        Transaction.TransactionArgument initialAmount = Transaction.TransactionArgument.newBuilder()
                .setType(Transaction.TransactionArgument.ArgType.U64)
                .setData(ByteString.copyFrom(ByteBuffer.allocate(Long.BYTES).order(ByteOrder.LITTLE_ENDIAN).putLong(0).order(ByteOrder.LITTLE_ENDIAN).array()))
                .build();

        // Create program
        Transaction.Program program = Transaction.Program.newBuilder()
                .addAllArguments(Arrays.asList(freshAddressArgument, initialAmount))
                .setCode(ByteString.copyFrom(Hex.decode(create_account_script)))
                .addAllModules(new ArrayList<>())
                .build();

        // Create raw transaction
        Transaction.RawTransaction rawTransaction = Transaction.RawTransaction.newBuilder()
                .setProgram(program)
                .setExpirationTime(600)
                .setGasUnitPrice(1)
                .setMaxGasAmount(6000)
                .setSenderAccount(ByteString.copyFrom(Hex.decode(existingAddress)))
                .setSequenceNumber(36)
                .build();

        // Create signed transaction
        Transaction.SignedTransaction signedTransaction = Transaction.SignedTransaction.newBuilder()
                .setRawTxnBytes(rawTransaction.toByteString())
                .setSenderPublicKey(ByteString.copyFrom(stripPublicKeyPrefix(publicKey.getEncoded())))
                .setSenderSignature(ByteString.copyFrom(signTransaction(rawTransaction, privateKey)))
                .build();

        AdmissionControlOuterClass.SubmitTransactionRequest submitTransactionRequest = AdmissionControlOuterClass.SubmitTransactionRequest.newBuilder()
                .setSignedTxn(signedTransaction)
                .build();

        AdmissionControlOuterClass.SubmitTransactionResponse response = stub.submitTransaction(submitTransactionRequest);

```

But I’m still getting an error saying: 
```
vm_status {
  validation {
    code: InvalidAuthKey
    message: "none"
  }
}

```
Can you spot what I’m doing wrong?

**Comment by ice09** [comment]
Please compare the linked `TransferExample` code, I suspect you are using the wrong Move script (as it is called `create_account_script` - this is not what should be called, but p2p-transfer: https://github.com/ketola/jlibra/blob/master/src/main/resources/move/peer_to_peer_transfer.mvir

We are not creating accounts here, just transferring coins.

**Comment by Ade92** [comment]
Yes, you are right, I'm using the create account move script as I need to create fresh accounts first, then transfer coins. How did you create your account from which you are sending coins?

**Comment by ice09** [comment]
You don't have to. The sequence would be like this:

1. Create public/private key pair with jlibra `GenerateKeys`. The address is printed out, this is your "account" (from now on ACCOUNT_ADDRESS).
2. Start Libra CLI (local or against Libra Testnet).
3. Call `account mint <ACCOUNT_ADDRESS> 100`, this will ask the faucet to transfer 100 Testnet-Coins to your ACCOUNT_ADDRESS
4. Check with `query balance <ACCOUNT_ADDRESS>` if you got Testnet-Coins

Now you have money at your "account" ACCOUNT_ADDRESS and you can spend it with the corresponding private key.   
Note: You cannot transfer the Coins in the CLI for now as the CLI lets you transfer with real accounts only.

But of course you can do this:

5. Create new account in CLI with `account create`.
6. Transfer Testnet-Coins from your ACCOUNT_ADDRESS to the CLI-created address.

Now you can also send the Testnet-Coins around in the CLI as well.

If this works for you I'd add it to a starter ("Usage") section in the README.

Note: Be aware that if your don't store your accounts in the CLI, they are lost after shutdown. You'ld have to `write` and `recover` using the CLI.

**Comment by Ade92** [comment]
I get it now. Thanks a lot!
